buildscript {
	repositories {
		google()
		mavenCentral()
	}
	dependencies {
		// Das Android-Gradle-Plugin, das Gradle beibringt, wie man Android-APKs baut
		classpath 'com.android.tools.build:gradle:8.11.2'
	}
}

apply plugin: 'com.android.application'

android {
	// Hier den Package-Namen aus Ihrer AndroidManifest.xml eintragen:
	namespace 'at.gaeckler.TessTacho'

	compileSdk 36

	defaultConfig {
		applicationId "at.gaeckler.TessTacho"
		minSdk 30
		targetSdk 36
		versionCode 6
		versionName "3.7.27"
		resValue "string", "app_version", versionName
	}

	sourceSets {
		main {
			// Sagt Gradle, dass die Dateiverzeichnisse aus dem alten ADT-Layout stammen:
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src']
			resources.srcDirs = ['src']
			aidl.srcDirs = ['src']
			renderscript.srcDirs = ['src']
			res.srcDirs = ['res']
			assets.srcDirs = ['assets']
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
	tasks.withType(JavaCompile) {
		options.compilerArgs << "-Xlint:deprecation"
	}
}